apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apexsaas
spec:
  replicas: 5
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10} # pause indefinitely
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: apexsaas
  template:
    metadata:
      labels:
        app: apexsaas
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: apexsaas
        ports:
        - containerPort: 3480
