apiVersion: apps/v1
kind: Deployment
metadata:
  name: apexsaas
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apexsaas
  template:
    metadata:
      labels:
        app: apexsaas
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: apexsaas
        ports:
        - containerPort: 80
