apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apexsaas
spec:
  replicas: 10
  selector:
    matchLabels:
      app: apexsaas
  template:
    metadata:
      labels:
        app: apexsaas
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: apexsaas
        ports:
        - containerPort: 33480
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1m # 1 hour
      - setWeight: 20
      - pause: {duration: 10} # pause indefinitely
