apiVersion: apps/v1
kind: Deployment
metadata:
  name: apexdemo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apexdemo
  template:
    metadata:
      labels:
        app: apexdemo
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: apexdemo
        ports:
        - containerPort: 80
